# Generated by Django 3.1 on 2020-08-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tempTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVacant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
                ('isVacant', models.BooleanField(default=True)),
                ('mentee', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mentee.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentee.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='JR', max_length=2)),
                ('rating', models.IntegerField(default=5)),
                ('comments', models.TextField(default='Add Comment', max_length=300)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentee.interview')),
            ],
        ),
    ]
