# Generated by Django 3.1 on 2020-08-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempTable',
        ),
    ]
