# Generated by Django 3.1 on 2020-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20200816_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='feedback',
            name='verdict',
            field=models.CharField(choices=[('SH', 'Strong Hire'), ('H', 'Hire'), ('LH', 'Leaning Hire'), ('NH', 'No Hire'), ('SNH', 'Strong No Hire')], default='H', max_length=20),
        ),
    ]
